spring:
  application:
    name: service0 # service0-copy 和 service0 applicationName一样一样，做均衡负载测试用
eureka:
  client:
    serviceUrl:
      defaultZone: http://spcloud:123456@localhost:8080/eureka/  #注册中心地址
    healthcheck:
      enabled: false # 健康检查
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.ip-address}:${server.port}
    ip-address: localhost
    prefer-ip-address: true
    health-check-url: http://${eureka.instance.ip-address}:${server.port}/health  # 健康信息指示器
    status-page-url: http://${eureka.instance.ip-address}:${server.port}/info    # 状态页指示器
    lease-expiration-duration-in-seconds: 90 # 续约到期时间（默认90秒）
    lease-renewal-interval-in-seconds: 30
server:
  port: 8082
info:
   build:
     names: 服务提供者1副本
     version: 1.0.0
