spring:
  application:
    name: service-version
  http:
    encoding:
       force: true
       charset: UTF-8
       enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://spcloud:123456@localhost:8080/eureka/  #注册中心地址
  instance:
    hostname: localhost
    ip-address: localhost
    instance-id: ${eureka.instance.ip-address}:${server.port}
    prefer-ip-address: true
server:
  port: 8086
  tomcat:
    uri-encoding: utf-8
info:
   build:
     names: 自定义路由
     version: 1.0.0